on: [push,pull_request]
name: build and test app
jobs:
  build:
    name: install dependencies
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.1'
          channel: 'stable'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test

      - name: install dependencies
        run: npm run init

      - name: run tests
        run: flutter test

      #      - name: build run
      #      - run: flutter run -t lib/main.dart --debug --flavor development
      #      - run: flutter run -t lib/main.dart --debug --flavor staging
      #      - run: flutter run -t lib/main.dart --debug --flavor preprod
      #      - run: flutter run -t lib/main.dart --debug --flavor release

      - name: build preprod
        run: flutter build apk -t lib/main.dart --flavor preprod
      - name: build release
        run: flutter build apk -t lib/main.dart --flavor release
